name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Set your PHP version

    - name: Install dependencies
      run: composer install

    - name: Start backend server
      run: |
        php -S 127.0.0.1:8000 -t public/ &  # Start the server in the background
        sleep 5  # Wait for the server to start

  frontend:
    runs-on: ubuntu-latest

    needs:
    - backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Set your Node.js version

    - name: Install npm dependencies
      run: |
        cd web-admin
        npm install

    - name: Start frontend server
      run: |
        cd web-admin
        ng serve --host 0.0.0.0 --port 4200 &  # Start the server in the background
        sleep 5  # Wait for the server to start
