name: CI/CD Pipeline

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Set your PHP version

    - name: Install dependencies
      run: |
        cd app
        composer install

    - name: Start backend server
      run: |
        php -S 127.0.0.1:8000 -t public/ &  # Start the server in the background
        sleep 5  # Wait for the server to start

  frontend:
    runs-on: ubuntu-latest

    needs:
    - backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Set your Node.js version

    - name: Install npm dependencies
      run: |
        cd web-admin
        npm install

    - name: Start frontend server
      run: |
        cd web-admin
        ng serve --host 0.0.0.0 --port 4200 &  # Start the server in the background
        sleep 5  # Wait for the server to start

  build-and-push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    needs: frontend
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Login to Dockerhub
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/green-quest -f ./docker/Dockerfile .
      - name: Push to Dockerhub
        if: ${{ !inputs.skip-push }}
        run: docker push ${{ secrets.DOCKER_USERNAME }}/green-quest
