name: CI/CD Pipeline

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    needs: frontend
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Login to Dockerhub
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/green-quest -f ./docker/Dockerfile .
      - name: Push to Dockerhub
        if: ${{ !inputs.skip-push }}
        run: docker push ${{ secrets.DOCKER_USERNAME }}/green-quest
